port = 8080
host = "localhost"
log_file = "logs.log"

[[model]]
name = "model1"
api_gateway = "http://localhost:8080"
type = "openai"
api_key = ""
model_name = "gpt-3.5-turbo"
max_tokens = 1000
temperature = 0.5
prompt = "Translate the following English text to French: 'Hello, how are you?'"
rate_limit = 10 # requests per second
endpoint = "/model1"