port = 8080
host = "localhost"
log_file = "logs.log"

[[models]]
name = "gpt-3.5-turbo"
base_url = "https://api.openai.com/v1"
type = "openai"
api_key = "your_api_key"
model_name = "gpt-3.5-turbo"
max_tokens = 1000
temperature = 0.5
prompt = "Translate the following %s text to %s: '%s', only return the translated text"
rate_limit = 10.0 # requests per second
endpoint = "/gpt-3.5-turbo"
